/**
 * @file ui.c
 * The watch face, the assistant face, and the morph between them.
 *
 * Clock view: hours left of centre, minutes right of it, the date below, and
 * a button that hands over to the assistant. Assistant view: the two digit
 * groups have become the assistant's two eyes, and the button reads Quit.
 *
 * The hour and minute groups are separate objects placed symmetrically about
 * the centre, because that is what lets them become a pair of eyes. Keep them
 * independent.
 *
 * Host-portable: no SDL, no ESP-IDF. See ui.h.
 */

#include "ui.h"

#include <stdbool.h>
#include <time.h>

#include "lvgl/lvgl.h"

/* Generated by tools/gen_fonts.py. Both have tabular figures: every digit has
 * the same advance, so nothing shifts as the time changes. */
LV_FONT_DECLARE(ui_font_digits_118);
LV_FONT_DECLARE(ui_font_date_94);

/* Amber-on-black, the way a VFD readout looks. */
#define UI_COLOR_BG     0x000000
#define UI_COLOR_AMBER  0xFFB000

/* The panel, same here as on the device — see main.c. */
#define UI_PANEL_WIDTH  410
#define UI_PANEL_HEIGHT 502

/* The cell and line height tools/gen_fonts.py reported for each font. */
#define UI_DIGIT_CELL_W 79
#define UI_GROUP_WIDTH  (2 * UI_DIGIT_CELL_W)
#define UI_GROUP_HEIGHT 85
#define UI_DATE_HEIGHT  88

/* The layout rule: nothing comes closer than this to an edge of the panel. It
 * puts the digit groups 94 px either side of the centre, leaving 30 px
 * between them, and lifts the button 32 px off the bottom. */
#define UI_EDGE_MARGIN    32
#define UI_GROUP_OFFSET_X (UI_PANEL_WIDTH / 2 - UI_EDGE_MARGIN - UI_GROUP_WIDTH / 2)

#define UI_BUTTON_WIDTH  220
#define UI_BUTTON_HEIGHT 64

/* Time above date, the pair centred in what the button leaves of the panel. */
#define UI_STACK_GAP 20
#define UI_STACK_TOP ((UI_PANEL_HEIGHT - UI_EDGE_MARGIN - UI_BUTTON_HEIGHT \
                       - (UI_GROUP_HEIGHT + UI_STACK_GAP + UI_DATE_HEIGHT)) / 2)
#define UI_TIME_OFFSET_Y (UI_STACK_TOP + UI_GROUP_HEIGHT / 2 - UI_PANEL_HEIGHT / 2)
#define UI_DATE_OFFSET_Y (UI_STACK_TOP + UI_GROUP_HEIGHT + UI_STACK_GAP \
                          + UI_DATE_HEIGHT / 2 - UI_PANEL_HEIGHT / 2)

/* The eye an hour or minute group turns into, and how long it takes. */
#define UI_EYE_SIZE 120
#define UI_MORPH_MS 400

#define UI_REFRESH_PERIOD_MS 1000

typedef enum {
    UI_VIEW_CLOCK,
    UI_VIEW_ASSISTANT,
} ui_view_t;

static lv_obj_t * hours_label;
static lv_obj_t * minutes_label;
static lv_obj_t * date_label;
static lv_obj_t * eyes[2];
static lv_obj_t * button_label;
static ui_view_t  view;

/* One property of one object, per animation frame. */
static void anim_opa(void * obj, int32_t value)
{
    lv_obj_set_style_opa(obj, (lv_opa_t) value, LV_PART_MAIN);
}

static void anim_width(void * obj, int32_t value)
{
    lv_obj_set_width(obj, value);
}

static void anim_height(void * obj, int32_t value)
{
    lv_obj_set_height(obj, value);
}

/* Every animation starts from where the property is now, so tapping again
 * mid-morph turns the movement around instead of jumping. lv_anim_start
 * replaces a running animation of the same object and property. */
static void morph(lv_obj_t * obj, lv_anim_exec_xcb_t exec, int32_t from, int32_t to)
{
    lv_anim_t anim;

    lv_anim_init(&anim);
    lv_anim_set_var(&anim, obj);
    lv_anim_set_exec_cb(&anim, exec);
    lv_anim_set_values(&anim, from, to);
    lv_anim_set_duration(&anim, UI_MORPH_MS);
    lv_anim_set_path_cb(&anim, lv_anim_path_ease_in_out);
    lv_anim_start(&anim);
}

static void fade(lv_obj_t * obj, lv_opa_t to)
{
    morph(obj, anim_opa, lv_obj_get_style_opa(obj, LV_PART_MAIN), to);
}

/* The clock and the assistant are the same two objects at the same two
 * places: the digits fade off while the box behind them grows square and
 * round into an eye, and back again. */
static void view_set(ui_view_t next)
{
    bool assistant = next == UI_VIEW_ASSISTANT;
    int i;

    view = next;

    fade(hours_label,   assistant ? LV_OPA_TRANSP : LV_OPA_COVER);
    fade(minutes_label, assistant ? LV_OPA_TRANSP : LV_OPA_COVER);
    fade(date_label,    assistant ? LV_OPA_TRANSP : LV_OPA_COVER);

    for (i = 0; i < 2; i++) {
        fade(eyes[i], assistant ? LV_OPA_COVER : LV_OPA_TRANSP);
        morph(eyes[i], anim_width, lv_obj_get_width(eyes[i]),
              assistant ? UI_EYE_SIZE : UI_GROUP_WIDTH);
        morph(eyes[i], anim_height, lv_obj_get_height(eyes[i]),
              assistant ? UI_EYE_SIZE : UI_GROUP_HEIGHT);
    }

    lv_label_set_text(button_label, assistant ? "Quit" : "Hey Kai");
}

static void button_clicked(lv_event_t * event)
{
    LV_UNUSED(event);

    view_set(view == UI_VIEW_CLOCK ? UI_VIEW_ASSISTANT : UI_VIEW_CLOCK);
}

static lv_obj_t * digits_create(lv_obj_t * parent, int32_t offset_x)
{
    lv_obj_t * label = lv_label_create(parent);

    lv_obj_set_style_text_font(label, &ui_font_digits_118, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(label, "00"); /* the font holds digits only */

    lv_obj_align(label, LV_ALIGN_CENTER, offset_x, UI_TIME_OFFSET_Y);

    return label;
}

static lv_obj_t * date_create(lv_obj_t * parent)
{
    lv_obj_t * label = lv_label_create(parent);

    lv_obj_set_style_text_font(label, &ui_font_date_94, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(label, "00/00");

    lv_obj_align(label, LV_ALIGN_CENTER, 0, UI_DATE_OFFSET_Y);

    return label;
}

/* An eye starts as the digit group's own box, invisible behind it, so the
 * morph is that box changing shape rather than a new thing appearing. */
static lv_obj_t * eye_create(lv_obj_t * parent, int32_t offset_x)
{
    lv_obj_t * eye = lv_obj_create(parent);

    lv_obj_remove_style_all(eye);
    lv_obj_remove_flag(eye, LV_OBJ_FLAG_CLICKABLE); /* decoration, not a target */
    lv_obj_set_size(eye, UI_GROUP_WIDTH, UI_GROUP_HEIGHT);
    lv_obj_align(eye, LV_ALIGN_CENTER, offset_x, UI_TIME_OFFSET_Y);
    lv_obj_set_style_bg_color(eye, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(eye, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_radius(eye, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_opa(eye, LV_OPA_TRANSP, LV_PART_MAIN);

    return eye;
}

static void button_create(lv_obj_t * parent)
{
    lv_obj_t * button = lv_button_create(parent);

    lv_obj_remove_style_all(button); /* the theme's blue is not this face */
    lv_obj_set_size(button, UI_BUTTON_WIDTH, UI_BUTTON_HEIGHT);
    lv_obj_align(button, LV_ALIGN_BOTTOM_MID, 0, -UI_EDGE_MARGIN);
    lv_obj_set_style_radius(button, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_border_width(button, 2, LV_PART_MAIN);
    lv_obj_set_style_border_color(button, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_obj_set_style_bg_color(button, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(button, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_bg_opa(button, LV_OPA_30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_add_event_cb(button, button_clicked, LV_EVENT_CLICKED, NULL);

    button_label = lv_label_create(button);
    lv_obj_set_style_text_font(button_label, &lv_font_montserrat_32, LV_PART_MAIN);
    lv_obj_set_style_text_color(button_label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(button_label, "Hey Kai");
    lv_obj_center(button_label);
}

static void clock_refresh(lv_timer_t * timer)
{
    LV_UNUSED(timer);

    time_t now = time(NULL);
    struct tm local;
    localtime_r(&now, &local);

    lv_label_set_text_fmt(hours_label, "%02d", local.tm_hour);
    lv_label_set_text_fmt(minutes_label, "%02d", local.tm_min);
    lv_label_set_text_fmt(date_label, "%02d/%02d", local.tm_mon + 1, local.tm_mday);
}

void ui_build(void)
{
    lv_obj_t * screen = lv_screen_active();
    lv_timer_t * timer;

    lv_obj_set_style_bg_color(screen, lv_color_hex(UI_COLOR_BG), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, LV_PART_MAIN);

    /* The eyes go on first so the digits fade off the front of them. */
    eyes[0] = eye_create(screen, -UI_GROUP_OFFSET_X);
    eyes[1] = eye_create(screen, UI_GROUP_OFFSET_X);

    hours_label   = digits_create(screen, -UI_GROUP_OFFSET_X);
    minutes_label = digits_create(screen, UI_GROUP_OFFSET_X);
    date_label    = date_create(screen);

    button_create(screen);
    view = UI_VIEW_CLOCK;

    timer = lv_timer_create(clock_refresh, UI_REFRESH_PERIOD_MS, NULL);
    lv_timer_ready(timer); /* draw the real time now, not a second from now */
}
