#!/usr/bin/env python3
"""Generate the fonts the watch face draws with.

LVGL ships Montserrat pre-generated up to 48 px, which is far too small on a
410 x 502 panel, so the clock digits and the date come from here instead. The
output is checked in; this is only needed to change a size. It wants node (the
converter comes from npm) and LVGL's own Montserrat, which lives in the
gitignored lvgl/ checkout.

    tools/gen_fonts.py

Both fonts get tabular figures: every digit is rewritten to one fixed advance
with its ink centred in that cell, the way the digit cells of a VFD sit.
Montserrat's figures are proportional — a '1' is little more than half the
width of a '0' — so without this a centred clock shifts sideways whenever a
digit changes, which at this size is impossible to miss. Punctuation keeps its
own advance: a '/' stranded in the middle of a digit cell just looks lost.

Changing a size here means changing three more places: the font name and the
metrics in ui.c, and the file name in CMakeLists.txt.
"""

import pathlib
import re
import subprocess
import sys

# Pinned like everything else here: a converter bump may change the emitted
# layout, and the rewrite below reads that layout.
CONVERTER = "lv_font_conv@1.5.3"

ROOT = pathlib.Path(__file__).resolve().parent.parent
TTF = ROOT / "lvgl" / "scripts" / "built_in_font" / "Montserrat-Medium.ttf"

# The clock digits, as large as a 32 px edge margin leaves room for.
TIME_SIZE = 118
# The date is 80% of that, and needs the '/' of MM/DD.
DATE_SIZE = round(TIME_SIZE * 0.8)

FONTS = [
    (TIME_SIZE, "0x30-0x39", "ui_font_digits_{}".format(TIME_SIZE)),
    (DATE_SIZE, "0x2F-0x39", "ui_font_date_{}".format(DATE_SIZE)),
]

# One entry of the emitted glyph_dsc[] table, in glyph id order. adv_w is 8.4
# fixed point: the stored value is 16 * pixels.
GLYPH_RE = re.compile(
    r"\{\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), "
    r"\.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)\}"
)

# One cmap entry, which is what says who is a digit: glyph id first_id + i
# holds the character range_start + i.
CMAP_RE = re.compile(
    r"\.range_start = (\d+), \.range_length = (\d+), \.glyph_id_start = (\d+)"
)


def digit_glyph_ids(source):
    """Glyph ids of '0'-'9', read from the font's own cmap."""
    cmaps = list(CMAP_RE.finditer(source))
    if not cmaps or source.count("LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY") != len(cmaps):
        sys.exit("cmap is not the plain contiguous form — has {} changed its "
                 "output format?".format(CONVERTER))

    ids = set()
    for m in cmaps:
        start, length, first_id = (int(g) for g in m.groups())
        for i in range(length):
            if 0x30 <= start + i <= 0x39:
                ids.add(first_id + i)
    return ids


def tabular(source):
    """Give every digit the widest digit's advance, ink centred in the cell."""
    digits = digit_glyph_ids(source)
    entries = list(GLYPH_RE.finditer(source))
    if not digits.issubset(range(len(entries))):
        sys.exit("cmap points past the end of glyph_dsc")

    cell = max(round(int(entries[i].group(2)) / 16) for i in digits)

    seen = [-1]

    def rewrite(m):
        seen[0] += 1
        if seen[0] not in digits:
            return m.group(0)
        box_w = int(m.group(3))
        return (
            "{{.bitmap_index = {}, .adv_w = {}, .box_w = {}, .box_h = {}, "
            ".ofs_x = {}, .ofs_y = {}}}"
        ).format(m.group(1), cell * 16, box_w, m.group(4),
                 (cell - box_w) // 2, m.group(6))

    return GLYPH_RE.sub(rewrite, source), cell


def generate(size, unicode_range, name):
    out = ROOT / "{}.c".format(name)

    # --no-kerning: tabular figures must not have pairs nudging digits back out
    # of their cells. --no-compress keeps the glyphs a plain byte array.
    subprocess.run(
        ["npx", "--yes", CONVERTER,
         "--font", str(TTF), "--range", unicode_range,
         "--size", str(size), "--bpp", "4",
         "--no-compress", "--no-prefilter", "--no-kerning",
         "--format", "lvgl", "--lv-font-name", name,
         "-o", str(out)],
        check=True,
    )

    source, cell = tabular(out.read_text())
    header = (
        "/* Generated by tools/gen_fonts.py — do not edit by hand.\n"
        " * Montserrat {} px, {}, digits rewritten to a fixed {} px advance so\n"
        " * that nothing shifts when a digit changes.\n"
        " */\n"
    ).format(size, unicode_range, cell)
    out.write_text(header + source)

    line_height = re.search(r"\.line_height = (\d+)", source).group(1)
    print("{}: {} px in a {} px cell, {} px line height".format(
        out.name, size, cell, line_height))


def main():
    if not TTF.exists():
        sys.exit("{} is missing — see CLAUDE.md for the lvgl/ checkout".format(TTF))
    for font in FONTS:
        generate(*font)


if __name__ == "__main__":
    main()
