#!/usr/bin/env python3
"""Generate the clock's digit font: Montserrat, digits only, monospaced.

Montserrat's figures are proportional — at 130 px a '1' is 48 px wide where a
'0' is 87 px — so a centred label shifts sideways every time a digit changes,
and at clock-face size the shift is impossible to miss. LVGL's converter has
no monospace switch, so this script runs it and then rewrites every glyph to
one fixed advance with its ink centred in that cell, the way the digit cells
of a VFD sit.

The result is checked in; this is only needed to change the size. It wants
node (the converter comes from npm) and LVGL's own Montserrat, which lives in
the gitignored lvgl/ checkout.

    tools/gen_digit_font.py             # rewrites ui_font_digits_130.c
    tools/gen_digit_font.py --size 96   # writes ui_font_digits_96.c
"""

import argparse
import pathlib
import re
import subprocess
import sys

# Pinned like everything else here: a converter bump may change the emitted
# layout, and the rewrite below reads that layout.
CONVERTER = "lv_font_conv@1.5.3"

ROOT = pathlib.Path(__file__).resolve().parent.parent
TTF = ROOT / "lvgl" / "scripts" / "built_in_font" / "Montserrat-Medium.ttf"
DIGITS = "0x30-0x39"
DIGIT_COUNT = 10

# One entry of the emitted glyph_dsc[] table. adv_w is 8.4 fixed point:
# the stored value is 16 * pixels.
GLYPH_RE = re.compile(
    r"\{\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), "
    r"\.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)\}"
)


def monospace(source, size):
    """Give every glyph the widest glyph's advance, ink centred in the cell."""
    glyphs = [m for m in GLYPH_RE.finditer(source) if int(m.group(3)) > 0]
    if len(glyphs) != DIGIT_COUNT:
        sys.exit(
            "expected {} glyphs, matched {} — has {} changed its output "
            "format?".format(DIGIT_COUNT, len(glyphs), CONVERTER)
        )

    cell = max(round(int(m.group(2)) / 16) for m in glyphs)

    def rewrite(m):
        box_w = int(m.group(3))
        if box_w == 0:
            return m.group(0)  # the reserved id-0 glyph stays empty
        return (
            "{{.bitmap_index = {}, .adv_w = {}, .box_w = {}, .box_h = {}, "
            ".ofs_x = {}, .ofs_y = {}}}"
        ).format(m.group(1), cell * 16, box_w, m.group(4),
                 (cell - box_w) // 2, m.group(6))

    header = (
        "/* Generated by tools/gen_digit_font.py — do not edit by hand.\n"
        " * Montserrat digits at {} px, every glyph rewritten to a fixed {} px\n"
        " * advance so the clock does not shift as the digits change.\n"
        " */\n"
    ).format(size, cell)

    return header + GLYPH_RE.sub(rewrite, source), cell


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--size", type=int, default=130, help="font size in px")
    parser.add_argument("-o", "--output", help="output path (default ui_font_digits_<size>.c)")
    args = parser.parse_args()

    out = pathlib.Path(args.output) if args.output else ROOT / "ui_font_digits_{}.c".format(args.size)
    name = out.stem

    if not TTF.exists():
        sys.exit("{} is missing — see CLAUDE.md for the lvgl/ checkout".format(TTF))

    # --no-kerning: a monospaced font must not have pairs nudging digits back
    # out of their cells. --no-compress keeps the glyphs a plain byte array.
    subprocess.run(
        ["npx", "--yes", CONVERTER,
         "--font", str(TTF), "--range", DIGITS,
         "--size", str(args.size), "--bpp", "4",
         "--no-compress", "--no-prefilter", "--no-kerning",
         "--format", "lvgl", "--lv-font-name", name,
         "-o", str(out)],
        check=True,
    )

    source, cell = monospace(out.read_text(), args.size)
    out.write_text(source)
    print("{}: {} px digits in a {} px cell".format(out.name, args.size, cell))


if __name__ == "__main__":
    main()
