/**
 * @file ui.c
 * The watch face, the assistant face, and the morph between them.
 *
 * Clock view: hours left of centre, minutes right of it, and the date and
 * its weekday below. Assistant view: the two digit groups have become the
 * assistant's two eyes. Four corner readouts sit above both, fed by
 * ui_status_set(): the radio and the charge along the top, the assistant's
 * speaker and microphone below.
 *
 * Neither face has anything to press. The watch changes view when the
 * platform hears its name and says so through ui_view_set(), so this file
 * only ever receives — see ui.h.
 *
 * The hour and minute groups are separate objects placed symmetrically about
 * the centre, because that is what lets them become a pair of eyes. Keep them
 * independent.
 *
 * Host-portable: no SDL, no ESP-IDF. See ui.h.
 */

#include "ui.h"

#include <stdbool.h>
#include <time.h>

#include "lvgl/lvgl.h"

/* Generated by tools/gen_fonts.py. The two digit fonts have tabular figures:
 * every digit has the same advance, so nothing shifts as the time changes. */
LV_FONT_DECLARE(ui_font_digits_118);
LV_FONT_DECLARE(ui_font_date_72);

/* The assistant's two ends, U+F028 and U+F130 from FontAwesome. LVGL's
 * built-in symbols have the speaker but no microphone at all, and the two
 * belong in one file: they are read together. */
LV_FONT_DECLARE(ui_font_assistant_18);
#define UI_SYMBOL_SPEAKER "\xEF\x80\xA8"
#define UI_SYMBOL_MIC     "\xEF\x84\xB0"

/* Amber-on-black, the way a VFD readout looks. */
#define UI_COLOR_BG     0x000000
#define UI_COLOR_AMBER  0xFFB000

/* The panel, same here as on the device — see main.c. */
#define UI_PANEL_WIDTH  410
#define UI_PANEL_HEIGHT 502

/* The cell and line height tools/gen_fonts.py reported for each font. */
#define UI_DIGIT_CELL_W   79
#define UI_GROUP_WIDTH    (2 * UI_DIGIT_CELL_W)
#define UI_GROUP_HEIGHT   85
#define UI_DATE_HEIGHT    69
#define UI_WEEKDAY_HEIGHT 44 /* LVGL's built-in Montserrat 40 */

/* The layout rule: nothing comes closer than this to an edge of the panel. It
 * puts the digit groups 94 px either side of the centre, leaving 30 px
 * between them, and holds the four corner readouts off the glass. */
#define UI_EDGE_MARGIN    32
#define UI_GROUP_OFFSET_X (UI_PANEL_WIDTH / 2 - UI_EDGE_MARGIN - UI_GROUP_WIDTH / 2)

/* The time, then the date and its weekday as one block beneath it — a wider
 * gap above the pair than inside it, so they read as one thing. The whole
 * stack is centred in the panel: nothing along the bottom reserves a strip of
 * it any more. */
#define UI_STACK_GAP 24
#define UI_DATE_GAP  8
#define UI_STACK_HEIGHT (UI_GROUP_HEIGHT + UI_STACK_GAP + UI_DATE_HEIGHT \
                         + UI_DATE_GAP + UI_WEEKDAY_HEIGHT)
#define UI_STACK_TOP ((UI_PANEL_HEIGHT - UI_STACK_HEIGHT) / 2)
#define UI_TIME_OFFSET_Y (UI_STACK_TOP + UI_GROUP_HEIGHT / 2 - UI_PANEL_HEIGHT / 2)
#define UI_DATE_OFFSET_Y (UI_STACK_TOP + UI_GROUP_HEIGHT + UI_STACK_GAP \
                          + UI_DATE_HEIGHT / 2 - UI_PANEL_HEIGHT / 2)
#define UI_WEEKDAY_OFFSET_Y (UI_STACK_TOP + UI_GROUP_HEIGHT + UI_STACK_GAP \
                             + UI_DATE_HEIGHT + UI_DATE_GAP \
                             + UI_WEEKDAY_HEIGHT / 2 - UI_PANEL_HEIGHT / 2)

/* The eye an hour or minute group turns into, and how long it takes. It is
 * narrower than the group's own box on purpose: two discs the width of the
 * digits read as two discs, and the black left between them is what makes the
 * pair read as a face. */
#define UI_EYE_SIZE 69
#define UI_MORPH_MS 400

/* The blink: the eye's height pulls in to a line and lets back out, then
 * holds open until the next one. */
#define UI_EYE_SHUT_H     12
#define UI_BLINK_MS       70
#define UI_BLINK_PAUSE_MS 3600

/* What is inside an eye, and what makes a disc one: a pupil with a catchlight
 * in it. Both are percentages, so every animation here still drives nothing
 * but the eye's own width and height.
 *
 * The percentage is of the eye's content box, and the lids are that box's
 * padding — half the shut height each, so the two of them meet exactly as the
 * blink bottoms out and the pupil is pinched to nothing instead of leaving a
 * slit across the closed line. */
#define UI_EYE_LID            (UI_EYE_SHUT_H / 2)
#define UI_PUPIL_PCT          50
#define UI_CATCHLIGHT_PCT     30 /* of the pupil */
#define UI_CATCHLIGHT_OFF_PCT (-20)

/* The corner readouts, in LVGL's built-in Montserrat because their symbols
 * come with it. A reading the platform does not have is dimmed, not hidden:
 * an empty corner reads as a bug, a dim one reads as "no". */
#define UI_STATUS_DIM LV_OPA_30

#define UI_REFRESH_PERIOD_MS 1000

typedef enum {
    UI_VIEW_CLOCK,
    UI_VIEW_ASSISTANT,
} ui_view_t;

static lv_obj_t * hours_label;
static lv_obj_t * minutes_label;
static lv_obj_t * date_label;
static lv_obj_t * weekday_label;
static lv_obj_t * wifi_label;
static lv_obj_t * battery_label;
static lv_obj_t * speaker_label;
static lv_obj_t * mic_label;
static ui_status_t status = { .battery_pct = -1 };
static lv_obj_t * eyes[2];
static ui_view_t  view;

/* One property of one object, per animation frame. */
static void anim_opa(void * obj, int32_t value)
{
    lv_obj_set_style_opa(obj, (lv_opa_t) value, LV_PART_MAIN);
}

static void anim_width(void * obj, int32_t value)
{
    lv_obj_set_width(obj, value);
}

static void anim_height(void * obj, int32_t value)
{
    lv_obj_set_height(obj, value);
}

/* Every animation starts from where the property is now, so a change of view
 * mid-morph turns the movement around instead of jumping. lv_anim_start
 * replaces a running animation of the same object and property. */
static void morph(lv_obj_t * obj, lv_anim_exec_xcb_t exec, int32_t from, int32_t to,
                  lv_anim_completed_cb_t completed)
{
    lv_anim_t anim;

    lv_anim_init(&anim);
    lv_anim_set_var(&anim, obj);
    lv_anim_set_exec_cb(&anim, exec);
    lv_anim_set_values(&anim, from, to);
    lv_anim_set_duration(&anim, UI_MORPH_MS);
    lv_anim_set_path_cb(&anim, lv_anim_path_ease_in_out);
    lv_anim_set_completed_cb(&anim, completed);
    lv_anim_start(&anim);
}

static void fade(lv_obj_t * obj, lv_opa_t to)
{
    morph(obj, anim_opa, lv_obj_get_style_opa(obj, LV_PART_MAIN), to, NULL);
}

/* Blinking runs off the same property as the morph, so switching back to the
 * clock replaces it and there is nothing to stop by hand. The first blink
 * waits out a full pause, so arriving in the assistant view is not a flicker. */
static void blink(lv_obj_t * eye)
{
    lv_anim_t anim;

    lv_anim_init(&anim);
    lv_anim_set_var(&anim, eye);
    lv_anim_set_exec_cb(&anim, anim_height);
    lv_anim_set_values(&anim, UI_EYE_SIZE, UI_EYE_SHUT_H);
    lv_anim_set_duration(&anim, UI_BLINK_MS);         /* the lid down */
    lv_anim_set_reverse_duration(&anim, UI_BLINK_MS); /* and back up */
    lv_anim_set_delay(&anim, UI_BLINK_PAUSE_MS);
    lv_anim_set_repeat_delay(&anim, UI_BLINK_PAUSE_MS);
    lv_anim_set_repeat_count(&anim, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&anim);
}

/* The end of an eye resize, either direction, so it has to ask which view
 * that resize was heading for. LVGL has already taken this animation off its
 * list, so starting the next one here is safe. */
static void blink_when_open(lv_anim_t * resize)
{
    if (view == UI_VIEW_ASSISTANT) blink(resize->var);
}

static lv_obj_t * digits_create(lv_obj_t * parent, int32_t offset_x)
{
    lv_obj_t * label = lv_label_create(parent);

    lv_obj_set_style_text_font(label, &ui_font_digits_118, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(label, "00"); /* the font holds digits only */

    lv_obj_align(label, LV_ALIGN_CENTER, offset_x, UI_TIME_OFFSET_Y);

    return label;
}

/* The date and the weekday: same treatment, different size and place. */
static lv_obj_t * stacked_create(lv_obj_t * parent, const lv_font_t * font,
                                 const char * text, int32_t offset_y)
{
    lv_obj_t * label = lv_label_create(parent);

    lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(label, text);

    lv_obj_align(label, LV_ALIGN_CENTER, 0, offset_y);

    return label;
}

/* The eye, the pupil in it and the catchlight in that are the same object
 * three times over. None of them is a touch target: the face is a thing to tap
 * later, and a decoration that swallowed the tap would be in the way. */
static lv_obj_t * disc_create(lv_obj_t * parent, int32_t w, int32_t h, uint32_t color)
{
    lv_obj_t * disc = lv_obj_create(parent);

    lv_obj_remove_style_all(disc);
    lv_obj_remove_flag(disc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_size(disc, w, h);
    lv_obj_set_style_bg_color(disc, lv_color_hex(color), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(disc, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_radius(disc, LV_RADIUS_CIRCLE, LV_PART_MAIN);

    return disc;
}

/* An eye starts as the digit group's own box, invisible behind it, so the
 * morph is that box changing shape rather than a new thing appearing.
 *
 * The pupil is a hole rather than a black disc — it is the background colour,
 * so it follows one. It and the catchlight follow the eye down and back out
 * for free, on the padding and the percentages above, and the whole of it
 * fades on one opacity, the eye's, because LVGL scales a child by its
 * parent's. So there is still one animation per property per eye. */
static lv_obj_t * eye_create(lv_obj_t * parent, int32_t offset_x)
{
    lv_obj_t * eye = disc_create(parent, UI_GROUP_WIDTH, UI_GROUP_HEIGHT, UI_COLOR_AMBER);
    lv_obj_t * pupil;
    lv_obj_t * catchlight;

    lv_obj_set_style_pad_all(eye, UI_EYE_LID, LV_PART_MAIN);

    pupil = disc_create(eye, lv_pct(UI_PUPIL_PCT), lv_pct(UI_PUPIL_PCT), UI_COLOR_BG);
    catchlight = disc_create(pupil, lv_pct(UI_CATCHLIGHT_PCT), lv_pct(UI_CATCHLIGHT_PCT),
                             UI_COLOR_AMBER);

    lv_obj_align(eye, LV_ALIGN_CENTER, offset_x, UI_TIME_OFFSET_Y);
    lv_obj_center(pupil);

    /* One light in the room, so both eyes catch it in the same corner. Offset
     * in percent for the same reason the sizes are: a blink has to take it
     * with it rather than leave it sitting outside a shut eye. */
    lv_obj_align(catchlight, LV_ALIGN_CENTER,
                 lv_pct(UI_CATCHLIGHT_OFF_PCT), lv_pct(UI_CATCHLIGHT_OFF_PCT));

    lv_obj_set_style_opa(eye, LV_OPA_TRANSP, LV_PART_MAIN);

    return eye;
}

/* The corner a readout sits in decides which way its margin points. */
static lv_obj_t * corner_create(lv_obj_t * parent, lv_align_t align,
                                const lv_font_t * font, const char * text)
{
    lv_obj_t * label = lv_label_create(parent);
    bool left = align == LV_ALIGN_TOP_LEFT || align == LV_ALIGN_BOTTOM_LEFT;
    bool top  = align == LV_ALIGN_TOP_LEFT || align == LV_ALIGN_TOP_RIGHT;

    lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_AMBER), LV_PART_MAIN);
    lv_label_set_text(label, text);
    lv_obj_align(label, align, left ? UI_EDGE_MARGIN : -UI_EDGE_MARGIN,
                 top ? UI_EDGE_MARGIN : -UI_EDGE_MARGIN);

    return label;
}

static const char * battery_symbol(void)
{
    if (status.charging) return LV_SYMBOL_CHARGE;
    if (status.battery_pct >= 90) return LV_SYMBOL_BATTERY_FULL;
    if (status.battery_pct >= 65) return LV_SYMBOL_BATTERY_3;
    if (status.battery_pct >= 40) return LV_SYMBOL_BATTERY_2;
    if (status.battery_pct >= 15) return LV_SYMBOL_BATTERY_1;
    return LV_SYMBOL_BATTERY_EMPTY;
}

/* Dimming is text_opa, not the object's opa, so it survives the view fades. */
static void status_refresh(void)
{
    if (wifi_label == NULL) return; /* status arrived before the UI existed */

    lv_obj_set_style_text_opa(wifi_label,
                              status.wifi_up ? LV_OPA_COVER : UI_STATUS_DIM, LV_PART_MAIN);
    lv_obj_set_style_text_opa(mic_label,
                              status.listening ? LV_OPA_COVER : UI_STATUS_DIM, LV_PART_MAIN);
    lv_obj_set_style_text_opa(speaker_label,
                              status.speaking ? LV_OPA_COVER : UI_STATUS_DIM, LV_PART_MAIN);

    if (status.battery_pct < 0) {
        lv_label_set_text_fmt(battery_label, "--%% %s", battery_symbol());
    }
    else {
        lv_label_set_text_fmt(battery_label, "%d%% %s", status.battery_pct, battery_symbol());
    }
}

static const char * const WEEKDAYS[] = {
    "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"
};

static void clock_refresh(lv_timer_t * timer)
{
    LV_UNUSED(timer);

    time_t now = time(NULL);
    struct tm local;
    localtime_r(&now, &local);

    lv_label_set_text_fmt(hours_label, "%02d", local.tm_hour);
    lv_label_set_text_fmt(minutes_label, "%02d", local.tm_min);
    lv_label_set_text_fmt(date_label, "%02d/%02d", local.tm_mon + 1, local.tm_mday);
    lv_label_set_text(weekday_label, WEEKDAYS[local.tm_wday % 7]);
}

void ui_build(void)
{
    lv_obj_t * screen = lv_screen_active();
    lv_timer_t * timer;

    lv_obj_set_style_bg_color(screen, lv_color_hex(UI_COLOR_BG), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, LV_PART_MAIN);

    /* The eyes go on first so the digits fade off the front of them. */
    eyes[0] = eye_create(screen, -UI_GROUP_OFFSET_X);
    eyes[1] = eye_create(screen, UI_GROUP_OFFSET_X);

    hours_label   = digits_create(screen, -UI_GROUP_OFFSET_X);
    minutes_label = digits_create(screen, UI_GROUP_OFFSET_X);
    date_label    = stacked_create(screen, &ui_font_date_72, "00/00", UI_DATE_OFFSET_Y);
    weekday_label = stacked_create(screen, &lv_font_montserrat_40, "---",
                                   UI_WEEKDAY_OFFSET_Y);

    wifi_label    = corner_create(screen, LV_ALIGN_TOP_LEFT,
                                  &lv_font_montserrat_18, LV_SYMBOL_WIFI);
    battery_label = corner_create(screen, LV_ALIGN_TOP_RIGHT,
                                  &lv_font_montserrat_18, "--%");
    speaker_label = corner_create(screen, LV_ALIGN_BOTTOM_LEFT,
                                  &ui_font_assistant_18, UI_SYMBOL_SPEAKER);
    mic_label     = corner_create(screen, LV_ALIGN_BOTTOM_RIGHT,
                                  &ui_font_assistant_18, UI_SYMBOL_MIC);
    status_refresh();

    view = UI_VIEW_CLOCK;

    timer = lv_timer_create(clock_refresh, UI_REFRESH_PERIOD_MS, NULL);
    lv_timer_ready(timer); /* draw the real time now, not a second from now */
}

/* The clock and the assistant are the same two objects at the same two
 * places: the digits fade off while the box behind them grows square and
 * round into an eye, and back again.
 *
 * The platform polls whatever it heard into here, so most calls say nothing
 * new and have to cost nothing — a morph restarted every frame would never
 * finish, and would take the blink down with it. */
void ui_view_set(bool assistant)
{
    ui_view_t next = assistant ? UI_VIEW_ASSISTANT : UI_VIEW_CLOCK;
    int i;

    if (hours_label == NULL) return; /* told before the UI existed */
    if (next == view) return;

    view = next;

    fade(hours_label,   assistant ? LV_OPA_TRANSP : LV_OPA_COVER);
    fade(minutes_label, assistant ? LV_OPA_TRANSP : LV_OPA_COVER);
    fade(date_label,    assistant ? LV_OPA_TRANSP : LV_OPA_COVER);
    fade(weekday_label, assistant ? LV_OPA_TRANSP : LV_OPA_COVER);

    for (i = 0; i < 2; i++) {
        fade(eyes[i], assistant ? LV_OPA_COVER : LV_OPA_TRANSP);
        morph(eyes[i], anim_width, lv_obj_get_width(eyes[i]),
              assistant ? UI_EYE_SIZE : UI_GROUP_WIDTH, NULL);
        morph(eyes[i], anim_height, lv_obj_get_height(eyes[i]),
              assistant ? UI_EYE_SIZE : UI_GROUP_HEIGHT, blink_when_open);
    }
}

void ui_status_set(const ui_status_t * next)
{
    status = *next;
    status_refresh();
}
